// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3hSakcDx0B_IT3Huw1Z_9MguKe5CbwgE',
    appId: '1:38395896470:web:2f149adba713e7335918b7',
    messagingSenderId: '38395896470',
    projectId: 'fir-databse-cc52d',
    authDomain: 'fir-databse-cc52d.firebaseapp.com',
    databaseURL: 'https://fir-databse-cc52d-default-rtdb.firebaseio.com',
    storageBucket: 'fir-databse-cc52d.firebasestorage.app',
    measurementId: 'G-85XLS19QH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATbg_htXJpnTp7b99tght3Rz4sllVQ0Xg',
    appId: '1:38395896470:android:409602dd12522cd15918b7',
    messagingSenderId: '38395896470',
    projectId: 'fir-databse-cc52d',
    databaseURL: 'https://fir-databse-cc52d-default-rtdb.firebaseio.com',
    storageBucket: 'fir-databse-cc52d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB91Yc5untFpZWHyO2wKnNjyviGlxtLJw',
    appId: '1:38395896470:ios:e046ecdbb8abdd735918b7',
    messagingSenderId: '38395896470',
    projectId: 'fir-databse-cc52d',
    databaseURL: 'https://fir-databse-cc52d-default-rtdb.firebaseio.com',
    storageBucket: 'fir-databse-cc52d.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB91Yc5untFpZWHyO2wKnNjyviGlxtLJw',
    appId: '1:38395896470:ios:e046ecdbb8abdd735918b7',
    messagingSenderId: '38395896470',
    projectId: 'fir-databse-cc52d',
    databaseURL: 'https://fir-databse-cc52d-default-rtdb.firebaseio.com',
    storageBucket: 'fir-databse-cc52d.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3hSakcDx0B_IT3Huw1Z_9MguKe5CbwgE',
    appId: '1:38395896470:web:e4de535d0db7835a5918b7',
    messagingSenderId: '38395896470',
    projectId: 'fir-databse-cc52d',
    authDomain: 'fir-databse-cc52d.firebaseapp.com',
    databaseURL: 'https://fir-databse-cc52d-default-rtdb.firebaseio.com',
    storageBucket: 'fir-databse-cc52d.firebasestorage.app',
    measurementId: 'G-T2VEV79KHC',
  );
}
